# Generated by Django 2.2 on 2021-09-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
