# Generated by Django 2.2 on 2021-09-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210915_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
