# Generated by Django 2.2 on 2021-09-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210916_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous Users', max_length=20),
        ),
    ]
