# Generated by Django 2.2 on 2021-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210909_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
