# Generated by Django 2.2 on 2021-09-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210914_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStamp',
        ),
    ]
